flags: {}
extra-package-dbs: []
packages:
- .
extra-deps:


flags:
    cryptonite:
        use_target_attributes: false
    crypton:
        support_aesni: false

allow-newer: true
resolver: lts-22.15
