name: "Build the ambiguity generator under nix"
on:
  pull_request:
  push:
jobs:
  tests:
    strategy:
      matrix:
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: "write"
      contents: "read"
    steps:
    - uses: actions/checkout@v4.1.1
    - uses: DeterminateSystems/nix-installer-action@v4
    - uses: DeterminateSystems/magic-nix-cache-action@v4
    - uses: DeterminateSystems/flake-checker-action@v4
    - name: Run nix build
      run: nix build .
